### ISSUE TITLE
[dev-frontend-zustand] Link zustand and backend api

### ISSUE THREAD

**Issue by rosyrosie** [swsnu/swppfall2022-team7#85]
Planning to use zustand for state management instead of redux
Use backend api and clean up dummy data

**Comment by rosyrosie** [comment]
Links for zustand

https://github.com/pmndrs/zustand
https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md#slices-pattern

**Comment by rosyrosie** [comment]
https://docs.pmnd.rs/zustand/guides/testing

**Comment by brighthonor** [comment]
Let's have a meeting for studying Zustand! It seems fun~!
